### ISSUE TITLE
[Feat] Default Configuration

### ISSUE THREAD

**Issue by Yushi5058** [brenoprata10/nvim-highlight-colors#105] opened 2024-06-23 00:34 UTC
Hello, 
I saw there is `exclude_filetypes`, why not make `filetypes` instead so I can define .html / .css files alone for example and not having to exclude every other filetype because it will be too much. 
Thank you, 
Yushi

**Comment by brenoprata10** [comment] 2024-06-23 08:55
Duplicate of https://github.com/brenoprata10/nvim-highlight-colors/issues/28

**Closed by brenoprata10** 2024-06-23 08:55 UTC
