### ISSUE TITLE
Bug: Invalid buffer id

### ISSUE THREAD

**Issue by aspeddro** [brenoprata10/nvim-highlight-colors#85] opened 2024-05-21 02:13 UTC
Neovim 0.10

```
Error executing vim.schedule lua callback: ...vim-highlight-colors/lua/nvim-highlight-colors/utils.lua:59: Invalid buffer id: 12
stack traceback:
        [C]: in function 'nvim_buf_get_extmarks'
        ...vim-highlight-colors/lua/nvim-highlight-colors/utils.lua:59: in function 'create_highlight'
        ...vim-highlight-colors/lua/nvim-highlight-colors/utils.lua:151: in function 'highlight_lsp_document_color'
        ...vim-highlight-colors/lua/nvim-highlight-colors/utils.lua:114: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp/client.lua:685: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by brenoprata10** [comment] 2024-05-21 07:47
Duplicate of https://github.com/brenoprata10/nvim-highlight-colors/issues/79
Update the plugin and the error will go away

**Closed by brenoprata10** 2024-05-21 07:47 UTC

**Comment by brenoprata10** [comment] 2024-05-21 12:38
I've pushed a fix to it. Could you update again and let me know if you're still getting this error?

**Comment by aspeddro** [comment] 2024-05-21 21:17
Fixed, Thanks!!
