### ISSUE TITLE
Slow scrolling when using virtual text compared to nvim-colorizer

### ISSUE THREAD

**Issue by Bekaboo** [brenoprata10/nvim-highlight-colors#103] opened 2024-06-15 07:54 UTC
When this plugin is enabled, the scrolling becomes slow when there are multiple virtual text highlight blocks on the screen compared to nvim-colorizer.

For example, try this file:

```lua
if vim.go.bg == 'dark' then
  c_autumnGreen  = '#76946a'
  c_autumnRed    = '#c34043'
  c_autumnYellow = '#dca561'
  c_carpYellow   = '#c8ae81'
  c_katanaGray   = '#717c7c'
  c_lotusBlue    = '#9fb5c9'
  c_lotusGray    = '#716e61'
  c_lotusRed0    = '#d7474b'
  c_lotusRed1    = '#e84444'
  c_lotusRed2    = '#d9a594'
  c_macroAqua    = '#95aeac'
  c_macroAsh     = '#626462'
  c_macroBg0     = '#0d0c0c'
  c_macroBg1     = '#181616'
  c_macroBg2     = '#201d1d'
  c_macroBg3     = '#282727'
  c_macroBg4     = '#393836'
  c_macroBg5     = '#625e5a'
  c_macroBlue0   = '#658594'
  c_macroBlue1   = '#8ba4b0'
  c_macroFg0     = '#c5c9c5'
  c_macroFg1     = '#b4b3a7'
  c_macroFg2     = '#a09f95'
  c_macroGray0   = '#a6a69c'
  c_macroGray1   = '#9e9b93'
  c_macroGray2   = '#7a8382'
  c_macroGreen0  = '#87a987'
  c_macroGreen1  = '#8a9a7b'
  c_macroOrange0 = '#b6927b'
  c_macroOrange1 = '#b98d7b'
  c_macroPink    = '#a292a3'
  c_macroRed     = '#c4746e'
  c_macroTeal    = '#949fb5'
  c_macroViolet  = '#8992a7'
  c_roninYellow  = '#ff9e3b'
  c_springBlue   = '#7fb4ca'
  c_springGreen  = '#98bb6c'
  c_springViolet = '#938aa9'
  c_sumiInk6     = '#54546d'
  c_waveAqua0    = '#6a9589'
  c_waveAqua1    = '#7aa89f'
  c_waveBlue0    = '#223249'
  c_waveBlue1    = '#2d4f67'
  c_waveRed      = '#e46876'
  c_winterBlue   = '#252535'
  c_winterGreen  = '#2e322d'
  c_winterRed    = '#43242b'
  c_winterYellow = '#322e29'
else
  c_autumnGreen  = '#969438'
  c_autumnRed    = '#b73242'
  c_autumnYellow = '#a0713c'
  c_carpYellow   = '#debe97'
  c_katanaGray   = '#717c7c'
  c_lotusBlue    = '#9fb5c9'
  c_lotusGray    = '#716e61'
  c_lotusRed0    = '#d7474b'
  c_lotusRed1    = '#e84444'
  c_lotusRed2    = '#d9a594'
  c_macroAqua    = '#586e62'
  c_macroAsh     = '#a0a0a0'
  c_macroBg0     = '#f6f6f6'
  c_macroBg1     = '#e7e7e7'
  c_macroBg2     = '#eeeeee'
  c_macroBg3     = '#d8d8d8'
  c_macroBg4     = '#c8c8c8'
  c_macroBg5     = '#a0a0a0'
  c_macroBlue0   = '#658594'
  c_macroBlue1   = '#537788'
  c_macroFg0     = '#1b1b1b'
  c_macroFg1     = '#303030'
  c_macroFg2     = '#787878'
  c_macroGray0   = '#827f79'
  c_macroGray1   = '#6e6b66'
  c_macroGray2   = '#7a8382'
  c_macroGreen0  = '#87a987'
  c_macroGreen1  = '#6a824f'
  c_macroOrange0 = '#a06c4e'
  c_macroOrange1 = '#825c45'
  c_macroPink    = '#a292a3'
  c_macroRed     = '#b23b34'
  c_macroTeal    = '#445f96'
  c_macroViolet  = '#373e50'
  c_roninYellow  = '#c87b2e'
  c_springBlue   = '#7fb4ca'
  c_springGreen  = '#98bb6c'
  c_springViolet = '#938aa9'
  c_sumiInk6     = '#b1b1d2'
  c_waveAqua0    = '#69827b'
  c_waveAqua1    = '#7aa89f'
  c_waveBlue0    = '#223249'
  c_waveBlue1    = '#2d4f67'
  c_waveRed      = '#e46876'
  c_winterBlue   = '#d4d4f0'
  c_winterGreen  = '#d5dcd2'
  c_winterRed    = '#e6c2c7'
  c_winterYellow = '#e2dcd4'
end
```

**Comment by brenoprata10** [comment] 2024-06-15 08:50
Duplicate of https://github.com/brenoprata10/nvim-highlight-colors/issues/80

**Closed by brenoprata10** 2024-06-15 08:50 UTC
